# Generated by Django 3.2.3 on 2021-06-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempresa', models.IntegerField()),
                ('identidad', models.IntegerField()),
                ('idmunicipio', models.IntegerField()),
                ('codigo_actividad', models.IntegerField()),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitd', models.FloatField()),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('colonia', models.CharField(max_length=200)),
                ('codigo_postal', models.IntegerField()),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
