# Generated by Django 3.2.3 on 2021-06-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_municipio_nombre_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
