# Generated by Django 3.2.3 on 2021-06-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_empresa_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
